#!/user/bin/env python

from os import path
from os import mkdir

import configparser
from DataRepository_research_themes.create_csv import create_csv

co_filename = __file__
co_dir = path.dirname(co_filename)


if __name__ == '__main__':

    config = configparser.ConfigParser()
    config.read(path.join(co_dir, 'default.ini'))

    url = config.get('global', 'url')
    outfile = config.get('global', 'outfile')
    log_dir = config.get('global', 'log_dir')
    if not path.exists(log_dir):
        mkdir(log_dir)
    logfile = config.get('global', 'logfile')

    create_csv(url, outfile, log_dir, logfile)
